name: Update README

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: jaywcjlove/github-action-readme@main
        with:
          start_marker: "<!--RECENT_ACTIVITY:start-->"
          end_marker: "<!--RECENT_ACTIVITY:end-->"
      
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
